
TwintopInsanityBarSettings = {
	["hasteApproachingThreshold"] = 135,
	["audio"] = {
		["s2mDeath"] = {
			["enabled"] = true,
			["sound"] = "Interface\\Addons\\TwintopInsanityBar\\wilhelm.ogg",
			["soundName"] = "Wilhelm Scream (TIB)",
		},
		["mindbender"] = {
			["sound"] = "Interface\\Addons\\TwintopInsanityBar\\BoxingArenaSound.ogg",
			["soundName"] = "Boxing Arena Gong (TIB)",
		},
	},
	["voidEruptionThreshold"] = true,
	["bar"] = {
		["borderFactor"] = 1,
		["xPos"] = 0,
		["dragAndDrop"] = false,
		["height"] = 24,
		["yPos"] = -152,
		["border"] = 1,
		["width"] = 245,
	},
	["displayText"] = {
		["fontSizeMiddle"] = 12,
		["fontSizeLock"] = true,
		["fontFaceLock"] = true,
		["fontSizeRight"] = 12,
		["middle"] = {
			["fontFace"] = "Interface\\AddOns\\ElvUI\\media\\fonts\\Expressway.ttf",
			["fontSize"] = 12,
			["inVoidformText"] = "$vfTime sec - $vfDrain/sec ",
			["fontFaceName"] = "Expressway",
			["outVoidformText"] = "{$liStacks}[$liStacks LI - $liTime sec]",
		},
		["right"] = {
			["fontFace"] = "Interface\\AddOns\\ElvUI\\media\\fonts\\Expressway.ttf",
			["fontSize"] = 12,
			["inVoidformText"] = "{$casting}[$casting + ]{$passive}[$passive + ]$insanity%",
			["fontFaceName"] = "Expressway",
			["outVoidformText"] = "{$casting}[$casting + ]{$passive}[$passive + ]$insanity%",
		},
		["left"] = {
			["fontFace"] = "Interface\\AddOns\\ElvUI\\media\\fonts\\Expressway.ttf",
			["fontSize"] = 12,
			["inVoidformText"] = "$haste%",
			["fontFaceName"] = "Expressway",
			["outVoidformText"] = "$haste%",
		},
		["fontSizeLeft"] = 12,
	},
	["showS2MSummary"] = true,
	["mindbender"] = {
		["enabled"] = true,
		["useNotification"] = {
			["enabled"] = false,
			["thresholdStacks"] = 26,
			["useVoidformStacks"] = false,
		},
		["timeMax"] = 3,
		["mode"] = "gcd",
		["swingsMax"] = 4,
		["gcdsMax"] = 2,
	},
	["textures"] = {
		["passiveBarName"] = "ElvUI Norm",
		["castingBar"] = "Interface\\AddOns\\ElvUI\\media\\textures\\normTex2.tga",
		["borderName"] = "1 Pixel",
		["border"] = "Interface\\Buttons\\WHITE8X8",
		["textureLock"] = true,
		["castingBarName"] = "ElvUI Norm",
		["insanityBarName"] = "ElvUI Norm",
		["passiveBar"] = "Interface\\AddOns\\ElvUI\\media\\textures\\normTex2.tga",
		["background"] = "Interface\\BUTTONS\\WHITE8X8.blp",
		["backgroundName"] = "ElvUI Blank",
		["insanityBar"] = "Interface\\AddOns\\ElvUI\\media\\textures\\normTex2.tga",
	},
	["colors"] = {
		["threshold"] = {
			["mindbender"] = "FFFF11FF",
			["over"] = "FF00FF00",
			["under"] = "4dbdbdbd",
		},
		["text"] = {
			["passiveInsanity"] = "FFDF00FF",
			["hasteBelow"] = "FFFFFFFF",
			["right"] = "FFFFFFFF",
			["left"] = "FFFFFFFF",
			["hasteAbove"] = "FF00FF00",
			["castingInsanity"] = "FFFFFFFF",
			["hasteApproaching"] = "FFFFFF00",
			["currentInsanity"] = "FFC2A3E0",
			["middle"] = "FFFFFFFF",
		},
		["bar"] = {
			["flashPeriod"] = 0.5,
			["inVoidform2GCD"] = "FFFFFF00",
			["enterVoidform"] = "FF5C2F89",
			["border"] = "ff000000",
			["inVoidform1GCD"] = "FFFF0000",
			["inVoidform"] = "ff431863",
			["flashEnabled"] = true,
			["background"] = "ff101010",
			["flashAlpha"] = 0.7,
			["casting"] = "ffffffff",
			["base"] = "FF763BAF",
			["passive"] = "FFDF00FF",
		},
	},
	["showSummary"] = false,
	["displayBar"] = {
		["alwaysShow"] = true,
		["notZeroShow"] = false,
	},
	["hastePrecision"] = 2,
	["ttd"] = {
		["numEntries"] = 50,
		["sampleRate"] = 0.2,
	},
	["auspiciousSpiritsTracker"] = true,
	["hasteThreshold"] = 140,
}
